# Generated by Django 4.0.4 on 2022-12-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ID', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('file_location', models.CharField(max_length=255)),
                ('file_state', models.CharField(max_length=255)),
                ('uploader', models.CharField(max_length=255)),
                ('related_project', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
