# Generated by Django 4.0.4 on 2022-12-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('property_name', models.CharField(max_length=255)),
                ('property_value', models.CharField(max_length=255)),
                ('sequence_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Model_structure_tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('associated_file_id', models.CharField(max_length=255)),
                ('sequence_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vault_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vault_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vault', models.CharField(max_length=255)),
            ],
        ),
    ]
